# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306e2b87406a94226792d0c82f95aefb773323c53a151e6c5cea10dc35a7b76f34a1bb3584f0a52849ccbfc7d0172d76934a6da65d8352d98c6c52b2ca3c234a

test:
  secret_key_base: a7542e08128dae16b03a51fc8cacf0cea97a98fe48a45972bd4aec26a7d75664fa2044ecff6286aab005ea4e6442ffed3c7b51f2ab8423732e5d96bbbcfe2c80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
